# Cloud Build configuration for Cloud Run (backend) + Firebase Hosting (frontend)
# Triggered by branch push: develop -> dev, main -> prod
# _ENV is overridden per trigger: dev for develop branch, prod for main branch

substitutions:
  _ENV: dev

steps:
  # Step 1: Build and deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        gcloud run deploy cally-backend-${_ENV} \
          --source . \
          --region us-central1 \
          --allow-unauthenticated \
          --set-secrets="FIREBASE_SERVICE_ACCOUNT=FIREBASE_SERVICE_ACCOUNT:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest" \
          --set-env-vars="NODE_ENV=${_ENV}" \
          --set-env-vars="^@^ALLOWED_ORIGINS=https://cally-658-dev.web.app,https://cally-658.web.app,capacitor://localhost,https://localhost"

        # Ensure traffic is routed to latest (needed when PR preview tags exist)
        gcloud run services update-traffic cally-backend-${_ENV} --region us-central1 --to-latest

  # Step 2: Get Cloud Run URL and Firebase config, create frontend env file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CLOUD_RUN_URL=$$(gcloud run services describe cally-backend-${_ENV} --region us-central1 --format='value(status.url)')
        FIREBASE_CONFIG=$$(gcloud secrets versions access latest --secret=FIREBASE_CLIENT_CONFIG)
        echo "VITE_API_URL=$${CLOUD_RUN_URL}/api" > /workspace/frontend/.env.production
        echo "VITE_FIREBASE_CONFIG=$${FIREBASE_CONFIG}" >> /workspace/frontend/.env.production
        echo "Created .env.production with API URL and Firebase config"
        cat /workspace/frontend/.env.production

  # Step 3: Install frontend dependencies and build
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        cat .env.production || echo "No .env.production found"
        npm ci
        npm run build

  # Step 4: Deploy frontend to Firebase Hosting
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting:${_ENV} --project cally-658

timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY
